name: Lint

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/lint.yml'
      - 'Sources/**/*.swift'
      - 'Tests/**/*.swift'
      - 'Package.swift'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/lint.yml'
      - 'Sources/**/*.swift'
      - 'Tests/**/*.swift'
      - 'Package.swift'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Bootstrap
      run: make bootstrap
      
    - name: Format
      run: make lint
      
