name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.10"

    - name: Run tests
      run: make test
