name: Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/tests-linux.yml'
      - 'Sources/**'
      - 'Tests/**'
      - 'Package.swift'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/tests-linux.yml'
      - 'Sources/**'
      - 'Tests/**'
      - 'Package.swift'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup swift
      run: |
        curl -L https://swift-server.github.io/swiftly/swiftly-install.sh -o swiftly-install.sh
        bash swiftly-install.sh --disable-confirmation --platform ubuntu22.04
        swiftly install 5.10-snapshot
        swiftly use 5.10-snapshot
        
    - name: Run tests
      run: make test
